title: Praveen Ranolia
description: [ I'm Praveen Ranolia, a 2023 graduate from IIT Roorkee with a deep foundation in mathematics and data analytics. I bring strong skills in Exploratory Data Analysis (EDA), Machine Learning (ML), and Data Structures & Algorithms (DSA), which have equipped me to solve complex data-driven problems. I'm currently looking to leverage these skills in a Data Science role, where I can contribute meaningfully to impactful projects and continue to grow as a data professional.]
theme: jekyll-theme-minimal
logo: assets/photo.png
minima: 
skin: dark 

# Include custom CSS files
include:  
  - assets/css/darkmode.css
# title: Praveen Ranolia
# remote_theme: jekyll/minima
# plugins:
#   - jekyll-remote-theme
# minima:
#   skin: dark # or auto if you want it to switch with your system settings.


