title: Praveen Ranolia
theme: jekyll-theme-minimal
logo: assets/photo.png

include:
  - assets/css/dark-mode.css

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default


